import turtle
turtle.Screen().bgcolor("lightblue")
t = turtle.Turtle()
t.speed(3)
for _ in range(4):
    t.forward(100)
    t.left(90)
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.fillcolor("brown")
turtle.begin_fill()
turtle.goto(50, 150)
turtle.goto(100, 100)
turtle.goto(0, 100)
turtle.end_fill()
turtle.penup()
turtle.goto(35, 0)
turtle.pendown()
turtle.fillcolor("orange")
turtle.begin_fill()

for _ in range(2):
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
turtle.end_fill()
turtle.hideturtle()
turtle.done()
